apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: starter-pack-listenerset
  namespace: ${namespace}
spec:
  parentRefs:
    - name: ${gateway_name}
      namespace: ${gateway_namespace}
  listeners:
%{ for hostname in hostnames ~}
    - name: http-starter-pack
      protocol: HTTP
      port: 80
      hostname: ${hostname}
%{ endfor ~}
